window.BS_I18N = {
  uz: {
    'nav.catalog': 'Katalog', 'nav.about': 'Biz haqimizda', 'nav.export': 'Eksport', 'nav.news': 'Yangiliklar', 'nav.contact': 'Aloqa', 'nav.home': 'Bosh sahifa', 'nav.call': 'Qo‘ng‘iroq',
    'ft.tag': 'Haqiqiy shokolad. O‘zbekistondan.', 'ft.pages': 'Sahifalar', 'ft.contact': 'Aloqa', 'ft.rights': 'Barcha huquqlar himoyalangan.', 'ft.top': 'Yuqoriga ↑',
    'skip': 'Asosiy qismga o‘tish',
    /* home */
    'hero.kicker': 'Shokolad fabrikasi · Toshkent', 'hero.cta1': 'Katalogni ko‘rish', 'hero.cta2': 'Hamkorlik', 'hero.pick': 'Mahsulotni tanlang', 'hero.badge': 'REAL CHOCOLATE INSIDE • SEA SALT CARAMEL • ',
    'sc.kicker': 'Kolleksiya', 'sc.title': 'Har bir rang — alohida kayfiyat', 'sc.details': 'Batafsil', 'sc.all': 'Butun katalog', 'sc.soon': 'Tez orada sotuvda', 'sc.scroll': 'Skroll qiling', 'sc.tap': 'Bosing — shokolad yog‘iladi',
    'ab.statement': 'BabuSweet — bu shunchaki shirinlik emas. Har bir luqmada haqiqiy shokolad, ipakdek karamel va O‘zbekiston hunarmandchiligi uyg‘unligi. Biz ichki bozorni sevimli mahsulot bilan to‘ldiramiz va eksport orqali dunyoga ta’m yetkazamiz.',
    'ab.more': 'Biz haqimizda', 'st.title': 'Raqamlarda',
    'par.kicker': 'Hamkorlik', 'par.title': 'Biznesingiz uchun uch yo‘nalish',
    'par.1t': 'Ulgurji savdo', 'par.1d': 'Do‘konlar, tarmoqlar va distribyutorlar uchun barqaror yetkazib berish.',
    'par.2t': 'Eksport', 'par.2d': 'Xalqaro hamkorlar uchun eksport hujjatlari va logistika.',
    'par.3t': 'Private label', 'par.3d': 'O‘z brendingiz ostida shokolad mahsuloti.',
    'news.kicker': 'Yangiliklar', 'news.title': 'Yaqinda yangilari chiqadi', 'news.all': 'Barcha yangiliklar', 'news.empty': 'Hozircha yangilik yo‘q', 'news.soon': 'Tez orada',
    'cta.kicker': 'Aloqa', 'cta.title': 'Hamkorlikni boshlaymiz', 'cta.btn': 'Bog‘lanish',
    /* catalog */
    'cat.kicker': 'Katalog', 'cat.title': 'Barcha mahsulotlar', 'cat.lead': 'BabuSweet — Sea Salt Caramel to‘ldirilgan shokolad konfetlar. O‘zingizga yoqqan rangni tanlang.',
    'cat.search': 'Mahsulot qidirish…', 'cat.all': 'Hammasi', 'cat.active': 'Sotuvda', 'cat.soon': 'Tez orada', 'cat.empty': 'Hech narsa topilmadi', 'cat.count': 'ta mahsulot', 'cat.ask': 'So‘rov', 'cat.view': 'Batafsil',
    /* product */
    'pr.back': 'Katalogga qaytish', 'pr.ask': 'So‘rov yuborish', 'pr.specs': 'Xususiyatlari', 'pr.flavor': 'Ta’mi', 'pr.weight': 'Og‘irligi', 'pr.category': 'Turi', 'pr.status': 'Holati',
    'pr.s.active': 'Sotuvda', 'pr.s.soon': 'Tez orada', 'pr.more': 'Boshqa mahsulotlar', 'pr.nf.t': 'Mahsulot topilmadi', 'pr.nf.d': 'Bunday mahsulot yo‘q yoki yashirilgan.', 'pr.tap': 'Bosing — shokolad yog‘iladi', 'pr.soon.note': 'Bu mahsulot tez orada sotuvga chiqadi.',
    /* about */
    'about.kicker': 'Biz haqimizda', 'about.title': 'Shokoladni sevib ishlaymiz',
    'about.p1': 'BabuSweet — Toshkent viloyati, Yangihayotda joylashgan shokolad mahsulotlari fabrikasi. Biz ichki bozor va eksport uchun ishlaymiz.',
    'about.p2': 'Maqsadimiz — har bir qadoqda bir xil sifat, ta’m va ishonch. Shuning uchun xomashyo tanlashdan tayyor mahsulotni jo‘natishgacha har bosqichni nazorat qilamiz.',
    'val.kicker': 'Qadriyatlar', 'val.title': 'Bizga ishonish sabablari',
    'val.1t': 'Haqiqiy shokolad', 'val.1d': 'Har bir konfetning ichida haqiqiy shokolad va sho‘r karamel mag‘iz.',
    'val.2t': 'Barqaror sifat', 'val.2d': 'Retsept va jarayonni nazorat qilamiz — har partiya bir xil ta’mda.',
    'val.3t': 'Ishonchli hamkor', 'val.3d': 'Ulgurji va eksport hamkorlar bilan ochiq, tushunarli shartlarda ishlaymiz.',
    'fac.kicker': 'Ishlab chiqarish', 'fac.title': 'Kakaodan qadoqgacha — nazorat ostida',
    'fac.1t': 'Xomashyo', 'fac.1d': 'Sifatli kakao va sut ingredientlarini tanlaymiz va qabul qilishda tekshiramiz.',
    'fac.2t': 'Tayyorlash', 'fac.2d': 'Shokolad massasi mayin va barqaror bo‘lishi uchun aniq retsept va harorat bilan tayyorlanadi.',
    'fac.3t': 'Shakllantirish', 'fac.3d': 'Karamel mag‘iz bilan to‘ldirilgan konfetlar zamonaviy liniyada shakllantiriladi.',
    'fac.4t': 'Qadoqlash', 'fac.4d': 'Mahsulot hidini va ta’mini saqlovchi himoyalangan qadoqda omborga yo‘l oladi.',
    'loc.kicker': 'Fabrika', 'loc.title': 'Yangihayot, Toshkent viloyati',
    /* export */
    'ex.kicker': 'Eksport va hamkorlik', 'ex.title': 'Toshkentdan dunyoga', 'ex.lead': 'Yangihayotdagi fabrikamizdan mahsulotlar ichki bozorga va xorijga yo‘l oladi. Hamkorlik yo‘nalishlarimiz kengayib bormoqda.',
    'ex.steps.kicker': 'Qanday ishlaymiz', 'ex.steps.title': 'Hamkorlik 4 qadamda',
    'ex.1t': 'So‘rov', 'ex.1d': 'Aloqa formasi yoki telefon orqali ehtiyojingizni yozing.',
    'ex.2t': 'Muhokama', 'ex.2d': 'Assortiment, hajm va yetkazib berish shartlarini kelishamiz.',
    'ex.3t': 'Shartnoma', 'ex.3d': 'Hujjatlar rasmiylashtiriladi va buyurtma ishlab chiqarishga topshiriladi.',
    'ex.4t': 'Yetkazib berish', 'ex.4d': 'Mahsulot tayyor bo‘lgach, logistikani birgalikda tashkil qilamiz.',
    'faq.title': 'Ko‘p so‘raladigan savollar',
    'faq.1q': 'Hamkorlikni qanday boshlayman?', 'faq.1a': 'Aloqa sahifasidagi formani to‘ldiring yoki bizga qo‘ng‘iroq qiling. Menejerimiz siz bilan bog‘lanadi.',
    'faq.2q': 'Mahsulot namunasini olsam bo‘ladimi?', 'faq.2a': 'Namuna masalasini hamkorlik so‘rovingizda yozing — shartlarni alohida kelishamiz.',
    'faq.3q': 'Private label qanday ishlaydi?', 'faq.3a': 'Siz brend va qadoq g‘oyasini taqdim etasiz, biz assortiment va ishlab chiqarishni birgalikda rejalashtiramiz.',
    'ex.cta': 'So‘rov yuborish',
    /* news */
    'nw.kicker': 'Yangiliklar', 'nw.title': 'Yangiliklar va e’lonlar', 'nw.lead': 'Yangi mahsulotlar, e’lonlar va fabrikadan xabarlar.',
    /* contact */
    'ct.kicker': 'Aloqa', 'ct.title': 'Keling, birga ishlaymiz', 'ct.phone': 'Telefon', 'ct.addr': 'Manzil', 'ct.hours': 'Ish vaqti', 'ct.map': 'Xaritada ochish',
    'f.name': 'Ismingiz', 'f.company': 'Kompaniya', 'f.contact': 'Telefon yoki Telegram', 'f.type': 'So‘rov turi', 'f.product': 'Mahsulot', 'f.msg': 'Xabar', 'f.send': 'Yuborish',
    'f.t1': 'Ulgurji savdo', 'f.t2': 'Eksport', 'f.t3': 'Private label', 'f.t4': 'Boshqa', 'f.none': '— tanlanmagan —',
    'f.err': 'Ism va aloqa ma’lumotini to‘ldiring', 'f.sending': 'Tayyorlanmoqda…',
    'f.copied': 'Xabar nusxalandi — Telegram ochildi, shu yerga qo‘yib yuboring.', 'f.ok2': 'Rahmat! Xabaringiz tayyorlandi.', 'f.callcopied': 'Xabar nusxalandi. Iltimos, bizga qo‘ng‘iroq qiling.', 'f.call': 'Iltimos, bizga qo‘ng‘iroq qiling.'
  },
  ru: {
    'nav.catalog': 'Каталог', 'nav.about': 'О нас', 'nav.export': 'Экспорт', 'nav.news': 'Новости', 'nav.contact': 'Контакты', 'nav.home': 'Главная', 'nav.call': 'Позвонить',
    'ft.tag': 'Настоящий шоколад. Из Узбекистана.', 'ft.pages': 'Страницы', 'ft.contact': 'Контакты', 'ft.rights': 'Все права защищены.', 'ft.top': 'Наверх ↑',
    'skip': 'Перейти к содержимому',
    'hero.kicker': 'Шоколадная фабрика · Ташкент', 'hero.cta1': 'Смотреть каталог', 'hero.cta2': 'Сотрудничество', 'hero.pick': 'Выберите продукт', 'hero.badge': 'REAL CHOCOLATE INSIDE • SEA SALT CARAMEL • ',
    'sc.kicker': 'Коллекция', 'sc.title': 'Каждый цвет — отдельное настроение', 'sc.details': 'Подробнее', 'sc.all': 'Весь каталог', 'sc.soon': 'Скоро в продаже', 'sc.scroll': 'Листайте', 'sc.tap': 'Нажмите — польётся шоколад',
    'ab.statement': 'BabuSweet — это не просто сладость. В каждом кусочке настоящий шоколад, шелковистая карамель и мастерство Узбекистана. Мы наполняем внутренний рынок любимым продуктом и дарим вкус миру через экспорт.',
    'ab.more': 'О нас', 'st.title': 'В цифрах',
    'par.kicker': 'Сотрудничество', 'par.title': 'Три направления для вашего бизнеса',
    'par.1t': 'Опт', 'par.1d': 'Стабильные поставки для магазинов, сетей и дистрибьюторов.',
    'par.2t': 'Экспорт', 'par.2d': 'Экспортные документы и логистика для международных партнёров.',
    'par.3t': 'Private label', 'par.3d': 'Шоколадная продукция под вашим брендом.',
    'news.kicker': 'Новости', 'news.title': 'Скоро — новинки', 'news.all': 'Все новости', 'news.empty': 'Пока нет новостей', 'news.soon': 'Скоро',
    'cta.kicker': 'Контакты', 'cta.title': 'Начнём сотрудничество', 'cta.btn': 'Связаться',
    'cat.kicker': 'Каталог', 'cat.title': 'Вся продукция', 'cat.lead': 'BabuSweet — шоколадные конфеты с начинкой Sea Salt Caramel. Выберите свой цвет.',
    'cat.search': 'Поиск продукции…', 'cat.all': 'Все', 'cat.active': 'В продаже', 'cat.soon': 'Скоро', 'cat.empty': 'Ничего не найдено', 'cat.count': 'продуктов', 'cat.ask': 'Запрос', 'cat.view': 'Подробнее',
    'pr.back': 'Назад в каталог', 'pr.ask': 'Отправить запрос', 'pr.specs': 'Характеристики', 'pr.flavor': 'Вкус', 'pr.weight': 'Вес', 'pr.category': 'Категория', 'pr.status': 'Статус',
    'pr.s.active': 'В продаже', 'pr.s.soon': 'Скоро', 'pr.more': 'Другие продукты', 'pr.nf.t': 'Продукт не найден', 'pr.nf.d': 'Такого продукта нет или он скрыт.', 'pr.tap': 'Нажмите — польётся шоколад', 'pr.soon.note': 'Этот продукт скоро появится в продаже.',
    'about.kicker': 'О нас', 'about.title': 'Мы делаем шоколад с любовью',
    'about.p1': 'BabuSweet — фабрика шоколадной продукции в Янгихаёте, Ташкентская область. Мы работаем для внутреннего рынка и экспорта.',
    'about.p2': 'Наша цель — одинаковое качество, вкус и надёжность в каждой упаковке. Поэтому мы контролируем каждый этап — от выбора сырья до отгрузки.',
    'val.kicker': 'Ценности', 'val.title': 'Почему нам доверяют',
    'val.1t': 'Настоящий шоколад', 'val.1d': 'Внутри каждой конфеты — настоящий шоколад и солёная карамель.',
    'val.2t': 'Стабильное качество', 'val.2d': 'Мы контролируем рецептуру и процесс — вкус каждой партии одинаков.',
    'val.3t': 'Надёжный партнёр', 'val.3d': 'С оптовыми и экспортными партнёрами работаем на открытых и понятных условиях.',
    'fac.kicker': 'Производство', 'fac.title': 'От какао до упаковки — под контролем',
    'fac.1t': 'Сырьё', 'fac.1d': 'Отбираем качественное какао и молочные ингредиенты и проверяем их при приёмке.',
    'fac.2t': 'Приготовление', 'fac.2d': 'Шоколадная масса готовится по точному рецепту и температуре — мягкая и стабильная.',
    'fac.3t': 'Формование', 'fac.3d': 'Конфеты с карамельной начинкой формуются на современной линии.',
    'fac.4t': 'Упаковка', 'fac.4d': 'Продукт в защищённой упаковке, сохраняющей вкус и аромат, отправляется на склад.',
    'loc.kicker': 'Фабрика', 'loc.title': 'Янгихает, Ташкентская область',
    'ex.kicker': 'Экспорт и сотрудничество', 'ex.title': 'Из Ташкента — в мир', 'ex.lead': 'С нашей фабрики в Янгихаёте продукция уходит на внутренний рынок и за рубеж. Наши направления продолжают расширяться.',
    'ex.steps.kicker': 'Как мы работаем', 'ex.steps.title': 'Сотрудничество в 4 шага',
    'ex.1t': 'Запрос', 'ex.1d': 'Опишите потребность через форму или по телефону.',
    'ex.2t': 'Обсуждение', 'ex.2d': 'Согласуем ассортимент, объём и условия поставки.',
    'ex.3t': 'Договор', 'ex.3d': 'Оформляем документы и передаём заказ в производство.',
    'ex.4t': 'Поставка', 'ex.4d': 'Когда продукция готова, вместе организуем логистику.',
    'faq.title': 'Частые вопросы',
    'faq.1q': 'Как начать сотрудничество?', 'faq.1a': 'Заполните форму на странице контактов или позвоните нам. Менеджер свяжется с вами.',
    'faq.2q': 'Можно ли получить образец?', 'faq.2a': 'Напишите о образце в запросе — условия обсудим отдельно.',
    'faq.3q': 'Как работает private label?', 'faq.3a': 'Вы предоставляете идею бренда и упаковки, мы вместе планируем ассортимент и производство.',
    'ex.cta': 'Отправить запрос',
    'nw.kicker': 'Новости', 'nw.title': 'Новости и анонсы', 'nw.lead': 'Новинки, анонсы и новости с фабрики.',
    'ct.kicker': 'Контакты', 'ct.title': 'Давайте работать вместе', 'ct.phone': 'Телефон', 'ct.addr': 'Адрес', 'ct.hours': 'Часы работы', 'ct.map': 'Открыть на карте',
    'f.name': 'Ваше имя', 'f.company': 'Компания', 'f.contact': 'Телефон или Telegram', 'f.type': 'Тип запроса', 'f.product': 'Продукт', 'f.msg': 'Сообщение', 'f.send': 'Отправить',
    'f.t1': 'Опт', 'f.t2': 'Экспорт', 'f.t3': 'Private label', 'f.t4': 'Другое', 'f.none': '— не выбрано —',
    'f.err': 'Заполните имя и контакт', 'f.sending': 'Подготовка…',
    'f.copied': 'Сообщение скопировано — открыт Telegram, вставьте его там.', 'f.ok2': 'Спасибо! Сообщение подготовлено.', 'f.callcopied': 'Сообщение скопировано. Пожалуйста, позвоните нам.', 'f.call': 'Пожалуйста, позвоните нам.'
  },
  en: {
    'nav.catalog': 'Catalog', 'nav.about': 'About', 'nav.export': 'Export', 'nav.news': 'News', 'nav.contact': 'Contact', 'nav.home': 'Home', 'nav.call': 'Call us',
    'ft.tag': 'Real chocolate. From Uzbekistan.', 'ft.pages': 'Pages', 'ft.contact': 'Contact', 'ft.rights': 'All rights reserved.', 'ft.top': 'Back to top ↑',
    'skip': 'Skip to content',
    'hero.kicker': 'Chocolate factory · Tashkent', 'hero.cta1': 'Browse catalog', 'hero.cta2': 'Partner with us', 'hero.pick': 'Pick a product', 'hero.badge': 'REAL CHOCOLATE INSIDE • SEA SALT CARAMEL • ',
    'sc.kicker': 'Collection', 'sc.title': 'Every colour, its own mood', 'sc.details': 'Details', 'sc.all': 'Full catalog', 'sc.soon': 'Coming soon', 'sc.scroll': 'Scroll', 'sc.tap': 'Tap — it rains chocolate',
    'ab.statement': 'BabuSweet is more than a treat. Every bite is real chocolate, silky caramel and Uzbek craftsmanship. We keep the domestic market stocked with a favourite and carry the taste to the world through export.',
    'ab.more': 'About us', 'st.title': 'By the numbers',
    'par.kicker': 'Partnership', 'par.title': 'Three ways to work with us',
    'par.1t': 'Wholesale', 'par.1d': 'Reliable supply for shops, retail chains and distributors.',
    'par.2t': 'Export', 'par.2d': 'Export documents and logistics for international partners.',
    'par.3t': 'Private label', 'par.3d': 'Chocolate products under your own brand.',
    'news.kicker': 'News', 'news.title': 'New arrivals coming soon', 'news.all': 'All news', 'news.empty': 'No news yet', 'news.soon': 'Coming soon',
    'cta.kicker': 'Contact', 'cta.title': 'Let’s start working together', 'cta.btn': 'Get in touch',
    'cat.kicker': 'Catalog', 'cat.title': 'All products', 'cat.lead': 'BabuSweet — chocolate candies filled with Sea Salt Caramel. Pick your colour.',
    'cat.search': 'Search products…', 'cat.all': 'All', 'cat.active': 'Available', 'cat.soon': 'Coming soon', 'cat.empty': 'Nothing found', 'cat.count': 'products', 'cat.ask': 'Enquire', 'cat.view': 'Details',
    'pr.back': 'Back to catalog', 'pr.ask': 'Send an enquiry', 'pr.specs': 'Specifications', 'pr.flavor': 'Flavour', 'pr.weight': 'Weight', 'pr.category': 'Category', 'pr.status': 'Status',
    'pr.s.active': 'Available', 'pr.s.soon': 'Coming soon', 'pr.more': 'More products', 'pr.nf.t': 'Product not found', 'pr.nf.d': 'This product does not exist or is hidden.', 'pr.tap': 'Tap — it rains chocolate', 'pr.soon.note': 'This product will be available soon.',
    'about.kicker': 'About us', 'about.title': 'We make chocolate with love',
    'about.p1': 'BabuSweet is a chocolate factory in Yangihayot, Tashkent Region. We serve the domestic market and export.',
    'about.p2': 'Our goal is the same quality, taste and trust in every pack. That is why we control every stage, from ingredient selection to dispatch.',
    'val.kicker': 'Values', 'val.title': 'Why partners trust us',
    'val.1t': 'Real chocolate', 'val.1d': 'Real chocolate and salted caramel inside every candy.',
    'val.2t': 'Consistent quality', 'val.2d': 'We control recipe and process, so every batch tastes the same.',
    'val.3t': 'Reliable partner', 'val.3d': 'We work with wholesale and export partners on open, clear terms.',
    'fac.kicker': 'Production', 'fac.title': 'From cocoa to pack — under control',
    'fac.1t': 'Ingredients', 'fac.1d': 'We select quality cocoa and dairy ingredients and inspect them on arrival.',
    'fac.2t': 'Preparation', 'fac.2d': 'The chocolate mass is prepared with an exact recipe and temperature — smooth and stable.',
    'fac.3t': 'Moulding', 'fac.3d': 'Caramel-filled candies are formed on a modern production line.',
    'fac.4t': 'Packaging', 'fac.4d': 'Sealed in protective packs that keep aroma and taste, products head to the warehouse.',
    'loc.kicker': 'The factory', 'loc.title': 'Yangihayot, Tashkent Region',
    'ex.kicker': 'Export & partnership', 'ex.title': 'From Tashkent to the world', 'ex.lead': 'From our factory in Yangihayot, products reach the domestic market and beyond. Our partnership routes keep growing.',
    'ex.steps.kicker': 'How we work', 'ex.steps.title': 'Partnership in 4 steps',
    'ex.1t': 'Enquiry', 'ex.1d': 'Tell us what you need via the form or by phone.',
    'ex.2t': 'Discussion', 'ex.2d': 'We agree on range, volume and delivery terms.',
    'ex.3t': 'Contract', 'ex.3d': 'Documents are prepared and the order goes into production.',
    'ex.4t': 'Delivery', 'ex.4d': 'When the goods are ready, we organise logistics together.',
    'faq.title': 'Frequently asked questions',
    'faq.1q': 'How do I start a partnership?', 'faq.1a': 'Fill in the form on the contact page or call us. Our manager will get back to you.',
    'faq.2q': 'Can I get a sample?', 'faq.2a': 'Mention samples in your enquiry — we will agree terms separately.',
    'faq.3q': 'How does private label work?', 'faq.3a': 'You bring the brand and packaging idea; we plan the range and production together.',
    'ex.cta': 'Send an enquiry',
    'nw.kicker': 'News', 'nw.title': 'News & announcements', 'nw.lead': 'New products, announcements and news from the factory.',
    'ct.kicker': 'Contact', 'ct.title': 'Let’s work together', 'ct.phone': 'Phone', 'ct.addr': 'Address', 'ct.hours': 'Working hours', 'ct.map': 'Open in maps',
    'f.name': 'Your name', 'f.company': 'Company', 'f.contact': 'Phone or Telegram', 'f.type': 'Request type', 'f.product': 'Product', 'f.msg': 'Message', 'f.send': 'Send',
    'f.t1': 'Wholesale', 'f.t2': 'Export', 'f.t3': 'Private label', 'f.t4': 'Other', 'f.none': '— not selected —',
    'f.err': 'Please enter your name and contact', 'f.sending': 'Preparing…',
    'f.copied': 'Message copied — Telegram opened, paste it there.', 'f.ok2': 'Thank you! Your message is ready.', 'f.callcopied': 'Message copied. Please call us.', 'f.call': 'Please call us.'
  }
};
